apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app: {{ include "..name" . }}
    chart: {{ include "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster: {{ .Values.cluster }}
    name: {{ include "..name" . }}
    role: {{ .Values.role }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "..name" . }}
    release: {{ .Release.Name }}
    name: {{ include "..name" . }}
    role: {{ .Values.role }}